doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Entity'
                prefix: 'App\Domain\Entity'
                alias: App

# Mapowanie XML
# ( błąd: [critical] Uncaught Error: is_dir(): Argument #1 ($filename) must be of type string, int given
# przy komendzie: bin/console doctrine:schema:create )

# doctrine:
#     dbal:
#         url: '%env(resolve:DATABASE_URL)%'
#         types:
#             uuid: 'Ramsey\Uuid\Doctrine\UuidType'
#
#     orm:
#         auto_generate_proxy_classes: true
#         naming_strategy: 'doctrine.orm.naming_strategy.underscore_number_aware'
#         auto_mapping: true
#         mappings:
#             App:
#                 is_bundle: false
#                 type: 'xml'
#                 dir: '%kernel.project_dir%/config/doctrine'
#                 prefix: 'App\Domain\Entity'
#                 alias: 'App'